Show con_name;

CREATE PLUGGABLE DATABASE pdb_DejandoHuella
  ADMIN USER admin_Proyecto IDENTIFIED BY 12345
  ROLES = (dba)
  FILE_NAME_CONVERT = (
    'C:\APP\CASCA\PRODUCT\18.0.0\ORADATA\XE\PDBSEED\',
    'C:\APP\CASCA\PRODUCT\18.0.0\ORADATA\XE\PDB_DEJANDOHUELLA\'
  );

ALTER PLUGGABLE DATABASE pdb_DejandoHuella OPEN;
ALTER PLUGGABLE DATABASE pdb_DejandoHuella SAVE STATE;

ALTER SESSION SET CONTAINER = pdb_DejandoHuella;
CREATE USER admin_Proyecto IDENTIFIED BY 12345;
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO admin_Proyecto;


/* =========================================================
   2. CREACIÓN DE TABLESPACES
   ========================================================= */
   
CREATE TABLESPACE dejandoHuella_ts
DATAFILE 'C:\APP\CASCA\PRODUCT\18.0.0\ORADATA\XE\PDB_DEJANDOHUELLA\dejandoHuella_ts.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 20M MAXSIZE 500M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TABLESPACE dejandoHuella_idx
DATAFILE 'C:\\APP\\CASCA\\PRODUCT\\18.0.0\\ORADATA\\XE\\PDB_DEJANDOHUELLA\\dejandoHuella_idx.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 10M MAXSIZE 200M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;


CREATE TEMPORARY TABLESPACE dejandoHuella_temp
TEMPFILE 'C:\\APP\\CASCA\\PRODUCT\\18.0.0\\ORADATA\\XE\\PDB_DEJANDOHUELLA\\dejandoHuella_temp.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 10M MAXSIZE 200M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


SELECT tablespace_name FROM dba_tablespaces;

ALTER USER admin_Proyecto
DEFAULT TABLESPACE dejandoHuella_ts
TEMPORARY TABLESPACE dejandoHuella_temp
QUOTA UNLIMITED ON dejandoHuella_ts;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO admin_Proyecto;
GRANT UNLIMITED TABLESPACE TO admin_Proyecto;

/* =========================================================
   3. PERFILES
   ========================================================= */
   
CREATE PROFILE perfil_admin_Proyecto LIMIT
  SESSIONS_PER_USER 2
  IDLE_TIME 10
  CONNECT_TIME 60
  FAILED_LOGIN_ATTEMPTS 3
  PASSWORD_LIFE_TIME 180;
  

-- Perfil para usuarios regulares
CREATE PROFILE perfil_usuario_Proyecto LIMIT
  SESSIONS_PER_USER 3
  IDLE_TIME 20
  CONNECT_TIME 120
  FAILED_LOGIN_ATTEMPTS 5
  PASSWORD_LIFE_TIME 90;

-- Perfil para voluntarios
CREATE PROFILE perfil_voluntario_Proyecto LIMIT
  SESSIONS_PER_USER 2
  IDLE_TIME 30
  CONNECT_TIME 180
  FAILED_LOGIN_ATTEMPTS 5
  PASSWORD_LIFE_TIME 90;


ALTER SESSION SET CURRENT_SCHEMA = admin_Proyecto;
